// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
/*
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvbDTLy_Ho3V0lV1zkRhP3akvjsweFefA',
    appId: '1:546375723568:web:33e2c9991481922d7e5bf5',
    messagingSenderId: '546375723568',
    projectId: 'project-e0f4a',
    authDomain: 'project-e0f4a.firebaseapp.com',
    storageBucket: 'project-e0f4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDknJNf82wlcSGj20g5SQbhM-QQzHYKCMg',
    appId: '1:546375723568:android:1b20f5e04c607c9e7e5bf5',
    messagingSenderId: '546375723568',
    projectId: 'project-e0f4a',
    storageBucket: 'project-e0f4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlDajqoIl6OK5iBcyeJwHFMKlu7rbjFu8',
    appId: '1:546375723568:ios:4c69f38d732220c47e5bf5',
    messagingSenderId: '546375723568',
    projectId: 'project-e0f4a',
    storageBucket: 'project-e0f4a.appspot.com',
    androidClientId:
        '546375723568-dclb5l6ts937q7fk1e7oddlj056epikm.apps.googleusercontent.com',
    iosClientId:
        '546375723568-4v2aqp5o6tvsr8nirlsai9cmfvv888q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlDajqoIl6OK5iBcyeJwHFMKlu7rbjFu8',
    appId: '1:546375723568:ios:4c69f38d732220c47e5bf5',
    messagingSenderId: '546375723568',
    projectId: 'project-e0f4a',
    storageBucket: 'project-e0f4a.appspot.com',
    androidClientId:
        '546375723568-dclb5l6ts937q7fk1e7oddlj056epikm.apps.googleusercontent.com',
    iosClientId:
        '546375723568-4v2aqp5o6tvsr8nirlsai9cmfvv888q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
*/
